syntax = "proto3";

package tickets.v1;

option go_package = "polyglot-ticketing-v1/protogen/go/tickets/v1;ticketsv1";

service TicketsService {
  rpc CreateTicket(CreateTicketRequest) returns (CreateTicketResponse);
  rpc UpdateTicket(UpdateTicketRequest) returns (UpdateTicketResponse);
  rpc GetTicket(GetTicketRequest) returns (GetTicketResponse);
  rpc ListTickets(ListTicketsRequest) returns (ListTicketsResponse);
}

message CreateTicketRequest {
  string title = 1;
  int64 price = 2;
  string user_id = 3;
}

message CreateTicketResponse {
  string id = 1;
  string title = 2;
  int64 price = 3;
  string user_id = 4;
}

message UpdateTicketRequest {
  string id = 1;
  string title = 2;
  int64 price = 3;
  string user_id = 4;
}

message UpdateTicketResponse {
  Ticket ticket = 1;
}

message GetTicketRequest {
  string id = 1;
}

message GetTicketResponse {
  Ticket ticket = 1;
}

message ListTicketsRequest {}

message ListTicketsResponse {
  repeated Ticket tickets = 1;
}

message Ticket {
  string id = 1;
  string title = 2;
  int64 price = 3;
  string user_id = 4;
}
